### ISSUE TITLE
please guide me how its work

### ISSUE THREAD

**Issue by Ijazweb** [HenriqueBarucco/WhatsApp-GPT#1]
setup everything but WhatsApp connect but no any response

**Comment by HenriqueBarucco** [comment]
Hello, I create a README for this project.

About your issue, do you set the env file?

**Comment by Ijazweb** [comment]
yes
ORGANIZATION_ID="org-******"
OPENAI_KEY="sk-*********"
BOT_NUMBER="923024400706" // what will be BOT_NUMBER
PHONE_NUMBER="923024400706" // and what will be PHONE_NUMBER
